name: Build

on: 
  push:
    branches:
      - main
      - '*action*'

jobs:

  render:
    runs-on: ubuntu-latest
    container:
      image: patzm/tex-whale:latest
    permissions:
      contents: write
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: render
        run: ./gen && ./render
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "rendered/*.pdf"
      #     bodyFile: "body.md"
      #     token: ${{ secrets.YOUR_GITHUB_TOKEN }}
