name: Build

on: 
  push:
    branches:
      - main
      - '*action*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build on top of the LaTeX image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: patzm/my-tex-whale:latest

  render:
    runs-on: ubuntu-latest
    container:
      image: my-tex-whale
    permissions:
      contents: write
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: render
        run: ./gen && ./render
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "rendered/*.pdf"
      #     bodyFile: "body.md"
      #     token: ${{ secrets.YOUR_GITHUB_TOKEN }}
