name: Build

on: 
  push:
    branches:
      - main
      - '*action*'

jobs:

  render:
    runs-on: ubuntu-latest
    container:
      image: patzm/tex-whale:latest
    permissions:
      contents: write
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: generate tex files
        run: ./generate

      - name: render PDF files
        run: ./render

      - name: publish PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: rendered/*.pdf